export const NOTIFICATION_EVENTS = [
  {
    key: "followup_reminder",
    label: "Follow-up reminder",
    description: "Remind the lead's agent before a scheduled follow-up.",
    defaultLeadTimeMinutes: 15,
    hasTiming: true,
    bell: "general",
    availableRoles: ["lead_agent"],
    timingMode: "lead_time",
  },
  {
    key: "ticket_opened",
    label: "Ticket opened (needs assignment)",
    description: "A sales user opened a ticket that needs an admin to assign a developer.",
    defaultLeadTimeMinutes: 0,
    hasTiming: false,
    bell: "general",
    availableRoles: [],
    timingMode: "delay",
  },
  {
    key: "ticket_assigned",
    label: "Ticket assigned to you",
    description: "An admin assigned a ticket to you.",
    defaultLeadTimeMinutes: 0,
    hasTiming: false,
    bell: "general",
    availableRoles: ["ticket_assignee"],
    timingMode: "delay",
  },
  {
    key: "ticket_resolved",
    label: "Ticket resolved",
    description: "A developer resolved a ticket you opened.",
    defaultLeadTimeMinutes: 0,
    hasTiming: false,
    bell: "general",
    availableRoles: ["ticket_creator", "lead_agent"],
    timingMode: "delay",
  },
  {
    key: "ticket_reopened",
    label: "Ticket reopened",
    description: "A resolved ticket assigned to you was reopened.",
    defaultLeadTimeMinutes: 0,
    hasTiming: false,
    bell: "general",
    availableRoles: ["ticket_assignee"],
    timingMode: "delay",
  },
  {
    key: "ticket_overdue",
    label: "Ticket overdue",
    description: "A ticket passed its due date and was escalated.",
    defaultLeadTimeMinutes: 0,
    hasTiming: false,
    bell: "general",
    availableRoles: ["ticket_assignee"],
    timingMode: "delay",
  },
  {
    key: "feedback_submitted",
    label: "Feedback submitted",
    description: "A user submitted dashboard feedback.",
    defaultLeadTimeMinutes: 0,
    hasTiming: false,
    bell: "general",
    availableRoles: [],
    timingMode: "delay",
  },
  {
    key: "feedback_resolved",
    label: "Feedback resolved",
    description: "Your feedback was resolved.",
    defaultLeadTimeMinutes: 0,
    hasTiming: false,
    bell: "general",
    availableRoles: ["feedback_submitter"],
    timingMode: "delay",
  },
  {
    key: "website_ready",
    label: "Website ready",
    description: "A lead's website is ready (moved to Ready).",
    defaultLeadTimeMinutes: 0,
    hasTiming: false,
    bell: "website",
    availableRoles: ["lead_agent", "lead_closer"],
    timingMode: "none",
  },
  {
    key: "website_link_added",
    label: "Website link added",
    description: "A website link was set on a lead — the website is live.",
    defaultLeadTimeMinutes: 0,
    hasTiming: false,
    bell: "website",
    availableRoles: ["lead_agent", "lead_closer"],
    timingMode: "none",
  },
  {
    key: "website_custom_domain",
    label: "Website live on custom domain",
    description: "A lead's website was moved to a custom domain and is live.",
    defaultLeadTimeMinutes: 0,
    hasTiming: false,
    bell: "website",
    availableRoles: ["lead_agent", "lead_closer"],
    timingMode: "none",
  },
  {
    key: "lead_submitted",
    label: "New lead submitted",
    description: "A sales user created a new lead.",
    defaultLeadTimeMinutes: 0,
    hasTiming: false,
    bell: "general",
    availableRoles: ["lead_agent"],
    timingMode: "delay",
  },
  {
    key: "prelead_submitted",
    label: "New pre-lead submitted",
    description: "A user added a new pre-lead.",
    defaultLeadTimeMinutes: 0,
    hasTiming: false,
    bell: "general",
    availableRoles: [],
    timingMode: "delay",
  },
  {
    key: "lead_status_changed",
    label: "Lead status changed",
    description: "A lead moved to a new status.",
    defaultLeadTimeMinutes: 0,
    hasTiming: false,
    bell: "general",
    availableRoles: ["lead_agent", "lead_closer"],
    timingMode: "delay",
  },
  {
    key: "contract_sent",
    label: "Contract sent to client",
    description: "A contract was emailed to the client.",
    defaultLeadTimeMinutes: 0,
    hasTiming: false,
    bell: "general",
    availableRoles: ["lead_agent", "contract_creator"],
    timingMode: "delay",
  },
  {
    key: "contract_send_failed",
    label: "Contract failed to send",
    description: "Sending a contract to the client failed — the contract is still a draft.",
    defaultLeadTimeMinutes: 0,
    hasTiming: false,
    bell: "general",
    availableRoles: ["contract_creator"],
    timingMode: "delay",
  },
  {
    key: "mail_received",
    label: "New email received",
    description: "A new message arrived in your linked company mailbox.",
    defaultLeadTimeMinutes: 0,
    hasTiming: false,
    bell: "general",
    availableRoles: ["mailbox_owner"],
    timingMode: "delay",
  },
  {
    key: "mailbox_verification_failed",
    label: "Company mailbox verification failed",
    description: "IMAP/SMTP verification failed for a linked company mailbox.",
    defaultLeadTimeMinutes: 0,
    hasTiming: false,
    bell: "general",
    availableRoles: ["mailbox_owner"],
    timingMode: "delay",
  },
  {
    key: "email_verify_quota_low",
    label: "Email verification quota low",
    description: "A verification provider passed 80% of its free allowance, or is failing repeatedly.",
    defaultLeadTimeMinutes: 0,
    hasTiming: false,
    bell: "general",
    availableRoles: [],
    timingMode: "delay",
  },
  {
    key: "site_agent_run_ready",
    label: "AI site edit ready for review",
    description: "The AI agent finished editing a site from a ticket — review and deploy.",
    defaultLeadTimeMinutes: 0,
    hasTiming: false,
    bell: "website",
    availableRoles: ["ticket_assignee", "ticket_creator"],
    timingMode: "delay",
  },
  {
    key: "site_agent_run_failed",
    label: "AI site edit failed",
    description: "The AI agent could not complete a ticket's site edit.",
    defaultLeadTimeMinutes: 0,
    hasTiming: false,
    bell: "website",
    availableRoles: ["ticket_assignee"],
    timingMode: "delay",
  },
] as const;

export type NotificationEventKey = (typeof NOTIFICATION_EVENTS)[number]["key"];

export function eventDefault(key: string) {
  return NOTIFICATION_EVENTS.find((e) => e.key === key);
}
