import { LEAD_STATUSES } from "@/lib/leads/types";
import { catViewKey, catSetKey } from "@/lib/leads/categories";

export const PERMISSIONS = [
  { key: "leads.view", name: "View Leads", category: "leads" },
  { key: "leads.create", name: "Create Lead", category: "leads" },
  { key: "leads.edit", name: "Edit Lead", category: "leads" },
  { key: "leads.delete", name: "Delete Lead", category: "leads", is_sensitive: true },
  { key: "leads.status_change", name: "Change Lead Status", category: "leads" },
  { key: "leads.assign", name: "Assign / Reassign Lead", category: "leads", is_sensitive: true },
  { key: "leads.set_status", name: "Set Status on New Lead", category: "leads" },
  { key: "leads.view_all", name: "View All Agents' Leads", category: "leads" },
  { key: "leads.export", name: "Export Leads", category: "leads" },
  { key: "leads.duplicate.override", name: "Override Duplicate Lead Block", category: "leads", is_sensitive: true },
  { key: "leads.followup", name: "Log Lead Follow-ups", category: "leads" },
  { key: "leads.tags.view", name: "View & Filter Tags", category: "leads" },
  { key: "leads.tags.manage", name: "Manage Lead Tags", category: "leads" },
  { key: "leads.tags.view_all", name: "View All Users' Tags", category: "leads", is_sensitive: true },
  { key: "leads.tags.share", name: "Share Tags", category: "leads", is_sensitive: true },
  { key: "pre_leads.view", name: "View Pre-Leads", category: "pre_leads" },
  { key: "pre_leads.create", name: "Create Pre-Lead", category: "pre_leads" },
  { key: "pre_leads.edit", name: "Edit Pre-Lead", category: "pre_leads" },
  { key: "pre_leads.delete", name: "Delete Pre-Lead", category: "pre_leads", is_sensitive: true },
  { key: "pre_leads.followup", name: "Update Follow-up", category: "pre_leads" },
  { key: "analytics.view", name: "View Analytics", category: "analytics" },
  { key: "analytics.view_webcraft", name: "View WebCraft Analytics", category: "analytics" },
  { key: "analytics.view_deepseek", name: "View DeepSeek Analytics", category: "analytics" },
  { key: "analytics.view_all_agents", name: "View All-Agent Analytics", category: "analytics" },
  { key: "analytics.by_agent", name: "View By-Agent Analytics", category: "analytics", is_sensitive: true },
  { key: "reports.agent_periodic", name: "Agent Periodic Report", category: "analytics", is_sensitive: true },
  { key: "ai_tools.webcraft", name: "Use WebCraft", category: "ai_tools" },
  { key: "ai_tools.deepseek", name: "Use DeepSeek", category: "ai_tools" },
  { key: "wge.manage", name: "Manage Website Engine (WGE)", category: "ai_tools", is_sensitive: true },
  { key: "admin.users.view", name: "View Users", category: "admin" },
  { key: "admin.users.create", name: "Create Users", category: "admin", is_sensitive: true },
  { key: "admin.users.edit", name: "Edit Users", category: "admin" },
  { key: "admin.users.deactivate", name: "Deactivate Users", category: "admin", is_sensitive: true },
  { key: "admin.users.delete", name: "Delete Users", category: "admin", is_sensitive: true },
  { key: "admin.departments.manage", name: "Manage Departments", category: "admin", is_sensitive: true },
  { key: "admin.permissions.manage", name: "Manage Permissions", category: "admin", is_sensitive: true },
  { key: "admin.logs.view", name: "View Activity Log", category: "admin" },
  { key: "admin.import", name: "Import Leads", category: "admin", is_sensitive: true },
  { key: "admin.settings.manage", name: "Manage App Settings & Add-ons", category: "admin", is_sensitive: true },
  { key: "tickets.view", name: "View Tickets", category: "tickets" },
  { key: "tickets.create", name: "Open Tickets", category: "tickets" },
  { key: "tickets.assign", name: "Assign Tickets", category: "tickets", is_sensitive: true },
  { key: "tickets.resolve", name: "Resolve Tickets", category: "tickets" },
  { key: "tickets.view_all", name: "View All Tickets", category: "tickets", is_sensitive: true },
  { key: "feedback.submit", name: "Submit Feedback", category: "feedback" },
  { key: "feedback.manage", name: "Manage Feedback", category: "feedback", is_sensitive: true },
  { key: "admin.notifications.manage", name: "Manage Notification Rules", category: "admin", is_sensitive: true },
  { key: "dashboard.kpi.total_leads", name: "KPI: Total Leads", category: "dashboard" },
  { key: "dashboard.kpi.quoted_revenue", name: "KPI: Quoted Revenue", category: "dashboard" },
  { key: "dashboard.kpi.ready", name: "KPI: Ready Count", category: "dashboard" },
  { key: "dashboard.kpi.avg_rating", name: "KPI: Avg Rating", category: "dashboard" },
  { key: "dashboard.kpi.closed_revenue", name: "KPI: Closed Revenue", category: "dashboard" },
  { key: "dashboard.kpi.recurring_revenue", name: "KPI: Recurring (Yearly) Revenue", category: "dashboard" },
  { key: "dashboard.kpi.avg_deal_size", name: "KPI: Avg Deal Size", category: "dashboard" },
  { key: "dashboard.kpi.conversion_rate", name: "KPI: Conversion Rate", category: "dashboard" },
  { key: "dashboard.kpi.new_this_week", name: "KPI: New Leads This Week", category: "dashboard" },
  { key: "dashboard.kpi.overdue_followups", name: "KPI: Overdue Follow-ups", category: "dashboard" },
  { key: "dashboard.kpi.pickup_rate", name: "KPI: Pickup Rate", category: "dashboard" },
  { key: "dashboard.kpi.open_tickets", name: "KPI: Open Tickets", category: "dashboard" },
  { key: "dashboard.kpi.overdue_tickets", name: "KPI: Overdue Tickets", category: "dashboard" },
  { key: "dashboard.kpi.avg_resolution_time", name: "KPI: Avg Ticket Resolution Time", category: "dashboard" },
  { key: "dashboard.kpi.closed_in_period", name: "KPI: Closed (Period)", category: "dashboard" },
  { key: "dashboard.kpi.avg_time_to_close", name: "KPI: Avg Time To Close", category: "dashboard" },
  { key: "dashboard.kpi.drop_ratio", name: "KPI: Drop Ratio", category: "dashboard" },
  { key: "dashboard.kpi.avg_first_touch", name: "KPI: Avg Time To First Touch", category: "dashboard" },
  { key: "dashboard.strip.status", name: "Status Percentage Strip", category: "dashboard" },
  { key: "dashboard.chart.leads_over_time", name: "Chart: Leads Over Time", category: "dashboard" },
  { key: "dashboard.chart.pipeline_by_status", name: "Chart: Pipeline by Status", category: "dashboard" },
  { key: "dashboard.chart.leads_by_agent", name: "Chart: Leads by Agent", category: "dashboard" },
  { key: "dashboard.chart.site_type_split", name: "Chart: Site Type Split", category: "dashboard" },
  { key: "dashboard.chart.rating_distribution", name: "Chart: Rating Distribution", category: "dashboard" },
  { key: "dashboard.chart.fresh_vs_followup", name: "Chart: Fresh vs Follow-up", category: "dashboard" },
  { key: "dashboard.chart.revenue_by_status", name: "Chart: Revenue by Status", category: "dashboard" },
  { key: "dashboard.chart.ticket_status_split", name: "Chart: Ticket Status Split", category: "dashboard" },
  { key: "payments.view", name: "View Payment Links", category: "payments" },
  { key: "payments.manage", name: "Manage Payment Links", category: "payments", is_sensitive: true },
  { key: "mail.manage", name: "Manage Company Mailboxes", category: "mail", is_sensitive: true },
  { key: "integrations.manage", name: "Manage Integrations (Google, Templates)", category: "integrations", is_sensitive: true },
  { key: "contracts.view", name: "View Contracts", category: "contracts" },
  { key: "contracts.send", name: "Create & Send Contracts", category: "contracts", is_sensitive: true },
  { key: "templates.manage", name: "Manage Website Templates", category: "templates", is_sensitive: true },
  { key: "templates.generate", name: "Generate From Templates", category: "templates" },
  { key: "templates.deploy", name: "Deploy Generated Websites", category: "templates", is_sensitive: true },
  { key: "analytics.view_templates", name: "View Template Engine Analytics", category: "templates" },
  { key: "studio.manage", name: "Manage Site Studio (Template Engine v3)", category: "templates", is_sensitive: true },
  { key: "forms.view", name: "View Form Submissions", category: "forms" },
  { key: "forms.manage", name: "Manage Form Endpoints", category: "forms", is_sensitive: true },
] as const;

export type PermissionKey = (typeof PERMISSIONS)[number]["key"];

export const PERMISSION_CATEGORIES = ["leads", "pre_leads", "analytics", "ai_tools", "admin", "tickets", "feedback", "dashboard", "payments", "templates", "mail", "contracts", "integrations", "forms"] as const;

/**
 * Is this a grantable permission key? The static catalog plus the per-lead-
 * category keys (`leads.cat_view.*` / `leads.cat_set.*`, seeded by migration
 * 0011 and toggled in the same admin grids).
 */
export function isKnownPermissionKey(key: unknown): boolean {
  if (typeof key !== "string") return false;
  if (PERMISSIONS.some((p) => p.key === key)) return true;
  return LEAD_STATUSES.some((s) => key === catViewKey(s) || key === catSetKey(s));
}
