/**
 * Single source of truth for the app version and its release history.
 *
 * Scheme: v2.MINOR.PATCH
 *   - MINOR: a big change (a new feature or system). Resets PATCH to 0.
 *   - PATCH: a bug fix, a minor UI change, or a small addition.
 *
 * Add a new release to the TOP of CHANGELOG — APP_VERSION is derived from it.
 * Entries are user-facing release notes, not commit messages.
 */

export type ChangeKind = "feature" | "improvement" | "fix";

export interface ChangelogChange {
  kind: ChangeKind;
  text: string;
}

export interface ChangelogEntry {
  /** Semantic version without the leading "v", e.g. "2.6.1". */
  version: string;
  /** Release date, ISO calendar date, e.g. "2026-07-19". */
  date: string;
  /** Short release name. */
  title: string;
  changes: ChangelogChange[];
}

/** Release history, NEWEST FIRST. */
export const CHANGELOG: ChangelogEntry[] = [
  {
    version: "2.8.0",
    date: "2026-07-19",
    title: "Notifications & changelog",
    changes: [
      {
        kind: "feature",
        text: "An unread-mail badge in the sidebar and on the browser tab, so you can see new mail without opening the mailbox.",
      },
      {
        kind: "feature",
        text: "Notifications for incoming mail and for contract activity, delivered through the existing notification settings.",
      },
      {
        kind: "feature",
        text: "A version chip in the corner of the app that links to this public changelog.",
      },
      {
        kind: "improvement",
        text: "New mail is checked on a schedule in the background, so badges stay current while you work.",
      },
    ],
  },
  {
    version: "2.7.0",
    date: "2026-07-19",
    title: "In-dashboard mailbox",
    changes: [
      {
        kind: "feature",
        text: "Read your linked company inbox without leaving the dashboard, in a two-pane list and reading view.",
      },
      {
        kind: "feature",
        text: "Compose new messages and reply to threads directly from the mailbox.",
      },
      {
        kind: "feature",
        text: "Attach files to any message you send, with sent mail saved back to your Sent folder.",
      },
    ],
  },
  {
    version: "2.6.1",
    date: "2026-07-19",
    title: "Templates & sign-in fixes",
    changes: [
      {
        kind: "fix",
        text: "Connecting Google now returns you to the correct domain after consent instead of dropping you on the wrong address.",
      },
      {
        kind: "fix",
        text: "The contract templates page now explains exactly why a Drive folder lists no documents, instead of showing an empty list.",
      },
    ],
  },
  {
    version: "2.6.0",
    date: "2026-07-19",
    title: "Google Docs contract templates",
    changes: [
      {
        kind: "feature",
        text: "Connect your Google account and register contract templates straight from a Drive folder.",
      },
      {
        kind: "feature",
        text: "Every contract is generated by copying the template document, filling its {{placeholders}} from the lead and exporting a PDF.",
      },
      {
        kind: "feature",
        text: "A placeholder catalog showing what each template can use, including custom lead fields and date/time placeholders.",
      },
      {
        kind: "improvement",
        text: "Generated contracts are stored in their own Drive folder, keeping templates clean.",
      },
      {
        kind: "improvement",
        text: "Agents can adjust pricing on a contract to apply a discount before it goes out.",
      },
    ],
  },
  {
    version: "2.5.0",
    date: "2026-07-18",
    title: "Contract management",
    changes: [
      {
        kind: "feature",
        text: "Generate a contract from a lead's details, preview it, and email it from the agent's own mailbox.",
      },
      {
        kind: "feature",
        text: "Per-agent signatures applied to the contracts they send.",
      },
      {
        kind: "feature",
        text: "A contracts list across all leads, plus a “Contract Sent” badge on the leads that already have one.",
      },
    ],
  },
  {
    version: "2.4.0",
    date: "2026-07-18",
    title: "Company mailbox",
    changes: [
      {
        kind: "feature",
        text: "Link company email accounts to users, with credentials stored encrypted.",
      },
      {
        kind: "feature",
        text: "IMAP and SMTP verification at link time, so a broken mailbox is caught before anyone tries to send.",
      },
    ],
  },
  {
    version: "2.3.0",
    date: "2026-07-18",
    title: "Custom-domain transfer",
    changes: [
      {
        kind: "feature",
        text: "Move a finished site from its staging subdomain to the client's own domain, taking the files fresh from the live server and removing the subdomain afterwards.",
      },
      {
        kind: "feature",
        text: "Upload a custom ZIP to a new or existing subdomain for sites built outside the wizard.",
      },
    ],
  },
  {
    version: "2.2.1",
    date: "2026-07-18",
    title: "Accurate deploy status",
    changes: [
      {
        kind: "fix",
        text: "Deploys no longer report a false failure while the new site is still coming online — the reported status now matches reality.",
      },
    ],
  },
  {
    version: "2.2.0",
    date: "2026-07-18",
    title: "Website deployment",
    changes: [
      {
        kind: "feature",
        text: "Deploy a generated site to a staging subdomain in one click.",
      },
      {
        kind: "feature",
        text: "Redeploy in place or take a site down when it is no longer needed.",
      },
      {
        kind: "feature",
        text: "A deployments board listing every deployed site and its current state.",
      },
    ],
  },
  {
    version: "2.1.1",
    date: "2026-07-18",
    title: "Wizard & imagery polish",
    changes: [
      {
        kind: "improvement",
        text: "Image gathering is faster and far more reliable — the build no longer stalls while collecting and ranking photos.",
      },
      {
        kind: "fix",
        text: "The generated site's header now shows the business logo instead of the business name whenever a logo is available.",
      },
    ],
  },
  {
    version: "2.1.0",
    date: "2026-07-17",
    title: "Template Engine",
    changes: [
      {
        kind: "feature",
        text: "Generate a complete client website from a lead's details with a five-step operator wizard: setup, content, images, build and review.",
      },
      {
        kind: "feature",
        text: "A lead dossier that gathers everything known about the business and derives the site's pages automatically.",
      },
      {
        kind: "feature",
        text: "AI image gathering with vision-based ranking, so each page starts from strong, relevant photos.",
      },
      {
        kind: "feature",
        text: "Verification gates that check a build before it can be handed over.",
      },
    ],
  },
  {
    version: "2.0.0",
    date: "2026-07-16",
    title: "Core platform",
    changes: [
      {
        kind: "feature",
        text: "The leads pipeline: capture, categorise, follow up and track every lead through to close.",
      },
      {
        kind: "feature",
        text: "Tickets and payments, tied back to the leads and clients they belong to.",
      },
      {
        kind: "feature",
        text: "Analytics and dashboards for individual agents and for the company as a whole.",
      },
      {
        kind: "feature",
        text: "Departments and granular permissions controlling what each role can see and do.",
      },
      {
        kind: "feature",
        text: "In-app notifications for the events that matter to you.",
      },
    ],
  },
];

/** Current application version, derived from the newest changelog entry. */
export const APP_VERSION: string = CHANGELOG[0].version;

/** "2.6.1" -> "v2.6.1" (idempotent). */
export function formatVersion(v: string): string {
  const bare = v.startsWith("v") ? v.slice(1) : v;
  return `v${bare}`;
}

/** "2.6.1" -> [2, 6, 1]. Throws on anything that is not MAJOR.MINOR.PATCH. */
export function parseVersion(v: string): [number, number, number] {
  const bare = v.startsWith("v") ? v.slice(1) : v;
  const m = /^(\d+)\.(\d+)\.(\d+)$/.exec(bare);
  if (!m) throw new Error(`Invalid version: ${v}`);
  return [Number(m[1]), Number(m[2]), Number(m[3])];
}

/** Negative if a < b, positive if a > b, 0 if equal. */
export function compareVersions(a: string, b: string): number {
  const pa = parseVersion(a);
  const pb = parseVersion(b);
  for (let i = 0; i < 3; i++) {
    if (pa[i] !== pb[i]) return pa[i] - pb[i];
  }
  return 0;
}
